site_name: NL2SQL
docs_dir: docs

plugins:
    - search
    - mermaid2
    - awesome-pages
    - minify:
        minify_html: true
    - git-revision-date-localized:
        type: date


theme:
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - content.code.copy

  icon:
    # logo: material/book
    logo: divami-logo

  custom_dir: overrides/

markdown_extensions:
  - admonition
  - nl2br
  - def_list
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - overrides/mermaid-config.js