# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/0-greet.ipynb.

# %% auto 0
__all__ = ['greet_english', 'greet_spanish']

# %% ../../nbs/0-greet.ipynb 1
from .__pre_init__ import cli

# %% ../../nbs/0-greet.ipynb 2
@cli.command()
def greet_english(user) -> None:
    """
    Greet the user.
    """
    print(f"Hello, {user}!")


@cli.command()
def greet_spanish(user) -> None:
    """
    Greet the user in Spanish.
    """
    print(f"¡Hola, {user}!")
