name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Python venv
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements/docs.txt

      - name: Build site with MkDocs
        run: |
          source venv/bin/activate
          mkdocs build
          ls

      - name: Rename site to temp_project
        run: |
          mv site temp_project 
          ls

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: {{ cookiecutter.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: {{ cookiecutter.AWS_SECRET_ACCESS_KEY }}
          aws-region: {{ cookiecutter.AWS_REGION }}

      - name: Copy to S3
        run: |
          aws s3 sync ./temp_project s3://{{ cookiecutter.AWS_S3_BUCKET }}/temp_project

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id {{ cookiecutter.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"